"""Document-driven requirements analysis for remote A2A agents.

Produces a Chinese, structured ``RequirementAnalysisPackage`` (functional and
non-functional requirements, risks, traceability, test strategy) together with a
``mind_map`` tree that UIs can render directly. When an LLM callable is
available the analysis is generated by the LLM; otherwise a keyword-based
rule engine produces a reasonable fallback package.
"""

from __future__ import annotations

import json
import logging
import re
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from harness.models.agent_contracts import (
    MindMapNode,
    NonFunctionalRequirement,
    RequirementAnalysisPackage,
    RequirementItem,
    RequirementSpec,
    RequirementTrace,
    TestStrategy,
)

logger = logging.getLogger(__name__)

LLMCallable = Callable[[str, str], Awaitable[str]]


@dataclass(frozen=True)
class DocumentChunk:
    source: str
    heading: str
    text: str


FUNCTIONAL_KEYWORDS = {
    "api": "API 能力",
    "workflow": "工作流编排",
    "temporal": "Temporal 工作流控制",
    "agent": "Agent 能力",
    "a2a": "A2A 互操作",
    "runner": "执行 Runner",
    "artifact": "产物管理",
    "minio": "产物对象存储",
    "postgresql": "权威持久化",
    "redis": "实时事件投影",
    "gateway": "企业网关",
    "上传": "文档上传",
    "下载": "产物下载",
    "审批": "审批流程",
    "用户": "用户管理",
    "登录": "身份认证",
    "权限": "权限管理",
    "查询": "数据查询",
    "报告": "报告生成",
    "通知": "消息通知",
    "监控": "运行监控",
    "配置": "配置管理",
    "导入": "数据导入",
    "导出": "数据导出",
    "搜索": "搜索能力",
    "统计": "统计分析",
    "日志": "日志管理",
    "备份": "数据备份",
    "恢复": "数据恢复",
}

NFR_KEYWORDS = {
    "security": ("security", "安全"),
    "安全": ("security", "安全"),
    "isolation": ("isolation", "隔离"),
    "隔离": ("isolation", "隔离"),
    "otel": ("observability", "可观测性"),
    "observability": ("observability", "可观测性"),
    "可观测": ("observability", "可观测性"),
    "backup": ("disaster_recovery", "灾备"),
    "restore": ("disaster_recovery", "灾备"),
    "灾备": ("disaster_recovery", "灾备"),
    "rpo": ("disaster_recovery", "灾备"),
    "rto": ("disaster_recovery", "灾备"),
    "slo": ("reliability", "可靠性"),
    "dlq": ("reliability", "可靠性"),
    "幂等": ("reliability", "可靠性"),
    "performance": ("performance", "性能"),
    "capacity": ("performance", "性能"),
    "容量": ("performance", "性能"),
    "并发": ("performance", "性能"),
    "延迟": ("performance", "性能"),
    "可用性": ("reliability", "可靠性"),
}

NFR_CATEGORY_LABELS = {
    "security": "安全",
    "isolation": "隔离",
    "observability": "可观测性",
    "disaster_recovery": "灾备",
    "reliability": "可靠性",
    "performance": "性能",
}


class HarnessRequirementsAnalyzer:
    """Extract structured requirements and a test strategy from Harness docs."""

    _ANALYSIS_SYSTEM_PROMPT = """你是一名资深的需求分析专家。请基于用户提供的需求文档（可能包含 Markdown / 中文 / 英文）进行结构化需求分析。

要求：
1. 所有输出内容一律使用简体中文（ID、专有名词、技术术语可保留英文原文）。
2. 识别并整理功能需求（functional requirements）：为每条需求给出简洁的标题、中文描述、优先级（high/medium/low）、验收标准（2-4 条）、来源位置。
3. 识别非功能需求（NFR）：覆盖安全、隔离、可观测性、灾备、可靠性、性能等类别。
4. 识别项目假设（assumptions）与风险（risks），风险使用 RISK-xxx 编号并给出中文描述。
5. 生成测试策略（test_strategy）：包含目标、测试级别、进入/退出标准、覆盖目标、回归范围、自动化策略。
6. 建立需求到风险、需求到测试关注点的追踪关系（traceability）。
7. 生成一个 mind_map 树，根节点为主题，一级分支为：功能需求、非功能需求、风险、测试策略、追踪关系；每条需求/风险/策略条目作为其下一级子节点。

只输出一个 JSON 对象，不要输出任何额外文字、解释或 Markdown 代码块。JSON 结构：
{
  "summary": "中文摘要",
  "requirement_spec": {
    "requirements": [
      {"id": "REQ-001", "title": "标题", "description": "描述", "priority": "high|medium|low", "acceptance_criteria": ["验收标准1", "验收标准2"], "source_ref": "来源"}
    ],
    "assumptions": ["假设1"],
    "risks": ["RISK-001: 风险描述"],
    "references": []
  },
  "non_functional_requirements": [
    {"id": "NFR-001", "category": "security|isolation|observability|disaster_recovery|reliability|performance", "description": "中文描述", "priority": "high|medium|low", "acceptance_criteria": ["标准1"], "source_ref": "来源"}
  ],
  "test_strategy": {
    "objective": "目标",
    "levels": ["unit", "contract", "integration", "e2e", "regression"],
    "priority_model": "risk_based",
    "entry_criteria": ["进入标准"],
    "exit_criteria": ["退出标准"],
    "coverage_targets": ["覆盖目标"],
    "regression_scope": ["回归范围"],
    "automation_approach": ["自动化策略"]
  },
  "traceability": [
    {"requirement_id": "REQ-001", "risk_ids": ["RISK-001"], "test_focus": ["测试关注点"], "recommended_test_levels": ["unit", "e2e"]}
  ],
  "mind_map": {
    "id": "root",
    "label": "需求分析主题",
    "children": [
      {"id": "reqs", "label": "功能需求", "children": [{"id": "REQ-001", "label": "REQ-001 标题", "children": [{"id": "REQ-001-desc", "label": "描述"}]}]},
      {"id": "nfrs", "label": "非功能需求", "children": [{"id": "NFR-001", "label": "NFR-001 安全"}]},
      {"id": "risks", "label": "风险", "children": [{"id": "RISK-001", "label": "RISK-001 风险描述"}]},
      {"id": "strategy", "label": "测试策略", "children": [{"id": "objective", "label": "目标"}, {"id": "levels", "label": "测试级别"}]},
      {"id": "trace", "label": "追踪关系", "children": [{"id": "trace-1", "label": "REQ-001 → 测试关注点"}]}
    ]
  }
}
"""

    def __init__(
        self,
        llm_text_call: LLMCallable | None = None,
        system_prompt: str | None = None,
    ) -> None:
        """Initialize the analyzer.

        Args:
            llm_text_call: Optional ``async (system_prompt, user_message) -> str``
                callable. When set, analysis is generated by the LLM with the
                ``system_prompt`` (defaults to the built-in Chinese analysis
                prompt). When ``None``, the keyword-based rule engine is used.
            system_prompt: Custom system prompt overriding the built-in one.
        """
        self._llm_text_call = llm_text_call
        self._system_prompt = system_prompt or self._ANALYSIS_SYSTEM_PROMPT

    async def analyze_async(
        self,
        *,
        message: str,
        input_data: dict,
        workspace_root: Path | None = None,
    ) -> RequirementAnalysisPackage:
        """LLM-driven analysis; falls back to the rule engine on any failure."""
        if self._llm_text_call is not None:
            try:
                return await self._analyze_with_llm(
                    message=message,
                    input_data=input_data,
                    workspace_root=workspace_root,
                )
            except Exception as exc:  # pragma: no cover - defensive fallback
                logger.warning(
                    "LLM requirements analysis failed (%s) — falling back to rule engine",
                    exc,
                )
        return self.analyze(
            message=message,
            input_data=input_data,
            workspace_root=workspace_root,
        )

    def analyze(
        self,
        *,
        message: str,
        input_data: dict,
        workspace_root: Path | None = None,
    ) -> RequirementAnalysisPackage:
        workspace = workspace_root or Path.cwd()
        chunks = self._load_chunks(input_data, workspace)
        if not chunks:
            chunks = [DocumentChunk(source="message", heading="用户请求", text=message)]

        requirements = self._functional_requirements(chunks)
        nfrs = self._non_functional_requirements(chunks)
        risks = self._risks(chunks, nfrs)
        traces = self._traceability(requirements, risks)
        strategy = self._test_strategy(requirements, nfrs, risks)
        spec = RequirementSpec(
            requirements=requirements,
            assumptions=[
                "远程 A2A Agent 之间通过结构化 JSON 契约交互。",
                "PostgreSQL、Temporal 与 MinIO 仍是权威的生产数据平面。",
                "Redis 仅用于实时事件投影，不作为权威状态存储。",
            ],
            risks=risks,
        )
        return RequirementAnalysisPackage(
            requirement_spec=spec,
            non_functional_requirements=nfrs,
            test_strategy=strategy,
            traceability=traces,
            summary=(
                f"共分析 {len(chunks)} 个文档章节，识别出 {len(requirements)} 条功能需求、"
                f"{len(nfrs)} 条非功能需求、{len(risks)} 项风险。"
            ),
            mind_map=self._build_mind_map(
                title="需求分析",
                requirements=requirements,
                nfrs=nfrs,
                risks=risks,
                strategy=strategy,
                traces=traces,
            ),
        )

    # ─── LLM path ────────────────────────────────────────────

    async def _analyze_with_llm(
        self,
        *,
        message: str,
        input_data: dict,
        workspace_root: Path | None,
    ) -> RequirementAnalysisPackage:
        workspace = workspace_root or Path.cwd()
        chunks = self._load_chunks(input_data, workspace)
        if not chunks:
            chunks = [DocumentChunk(source="message", heading="用户请求", text=message)]

        document_text = "\n\n".join(
            f"### {chunk.source} / {chunk.heading}\n{chunk.text}" for chunk in chunks
        )
        user_message = (
            f"用户请求：{message}\n\n"
            f"需求文档内容如下：\n\n{document_text}"
        )
        raw = await self._llm_text_call(self._system_prompt, user_message)  # type: ignore[misc]
        payload = _extract_json_object(raw)
        payload["mind_map"] = self._build_mind_map_from_llm(payload)
        return RequirementAnalysisPackage.model_validate(payload)

    def _build_mind_map_from_llm(self, payload: dict[str, Any]) -> dict[str, Any]:
        """Normalize the LLM mind_map into the standard tree; fall back to a
        deterministic tree built from the parsed payload when absent/invalid."""
        candidate = payload.get("mind_map")
        if isinstance(candidate, dict) and isinstance(candidate.get("children"), list):
            normalized = self._normalize_mind_map_node(candidate)
            if normalized is not None:
                return normalized
        return self._build_mind_map(
            title=payload.get("summary") or "需求分析",
            requirements=_parse_requirements(payload),
            nfrs=_parse_nfrs(payload),
            risks=_parse_risks(payload),
            strategy=_parse_strategy(payload),
            traces=_parse_traces(payload),
        )

    def _normalize_mind_map_node(self, node: dict[str, Any]) -> dict[str, Any] | None:
        label = str(node.get("label") or "").strip()
        if not label:
            return None
        children = []
        for child in node.get("children") or []:
            if not isinstance(child, dict):
                continue
            normalized = self._normalize_mind_map_node(child)
            if normalized is not None:
                children.append(normalized)
        return {
            "id": str(node.get("id") or _slug(label)) or "node",
            "label": label,
            "children": children,
        }

    def _build_mind_map(
        self,
        *,
        title: str,
        requirements: list[RequirementItem],
        nfrs: list[NonFunctionalRequirement],
        risks: list[str],
        strategy: TestStrategy,
        traces: list[RequirementTrace],
    ) -> MindMapNode:
        req_children = [
            MindMapNode(
                id=req.id,
                label=f"{req.id} {req.title}",
                children=[
                    MindMapNode(id=f"{req.id}-desc", label=req.description),
                    MindMapNode(
                        id=f"{req.id}-ac",
                        label="验收标准",
                        children=[
                            MindMapNode(id=f"{req.id}-ac-{idx + 1}", label=ac)
                            for idx, ac in enumerate(req.acceptance_criteria)
                        ],
                    ),
                ],
            )
            for req in requirements
        ]
        nfr_children = [
            MindMapNode(
                id=nfr.id,
                label=f"{nfr.id} {NFR_CATEGORY_LABELS.get(nfr.category, nfr.category)}",
                children=[
                    MindMapNode(id=f"{nfr.id}-desc", label=nfr.description),
                    MindMapNode(
                        id=f"{nfr.id}-ac",
                        label="验收标准",
                        children=[
                            MindMapNode(id=f"{nfr.id}-ac-{idx + 1}", label=ac)
                            for idx, ac in enumerate(nfr.acceptance_criteria)
                        ],
                    ),
                ],
            )
            for nfr in nfrs
        ]
        risk_children = [
            MindMapNode(id=f"risk-{idx + 1}", label=risk) for idx, risk in enumerate(risks)
        ]
        strategy_children = [
            MindMapNode(id="strategy-objective", label=f"目标：{strategy.objective}"),
            MindMapNode(
                id="strategy-levels",
                label="测试级别",
                children=[
                    MindMapNode(id=f"level-{level}", label=level) for level in strategy.levels
                ],
            ),
            MindMapNode(
                id="strategy-coverage",
                label="覆盖目标",
                children=[
                    MindMapNode(id=f"coverage-{idx + 1}", label=item)
                    for idx, item in enumerate(strategy.coverage_targets)
                ],
            ),
            MindMapNode(
                id="strategy-automation",
                label="自动化策略",
                children=[
                    MindMapNode(id=f"automation-{idx + 1}", label=item)
                    for idx, item in enumerate(strategy.automation_approach)
                ],
            ),
        ]
        trace_children = [
            MindMapNode(
                id=f"trace-{trace.requirement_id}",
                label=trace.requirement_id,
                children=[
                    MindMapNode(id=f"trace-{trace.requirement_id}-{idx + 1}", label=focus)
                    for idx, focus in enumerate(trace.test_focus[:4])
                ],
            )
            for trace in traces
        ]
        return MindMapNode(
            id="root",
            label=title,
            children=[
                MindMapNode(
                    id="reqs",
                    label=f"功能需求（{len(requirements)}）",
                    children=req_children,
                ),
                MindMapNode(
                    id="nfrs",
                    label=f"非功能需求（{len(nfrs)}）",
                    children=nfr_children,
                ),
                MindMapNode(
                    id="risks",
                    label=f"风险（{len(risks)}）",
                    children=risk_children,
                ),
                MindMapNode(
                    id="strategy",
                    label="测试策略",
                    children=strategy_children,
                ),
                MindMapNode(
                    id="traces",
                    label=f"追踪关系（{len(traces)}）",
                    children=trace_children,
                ),
            ],
        )

    # ─── Rule engine (fallback) ──────────────────────────────

    def _load_chunks(self, input_data: dict, workspace: Path) -> list[DocumentChunk]:
        chunks: list[DocumentChunk] = []
        for item in input_data.get("documents", []):
            if isinstance(item, dict):
                source = str(item.get("path") or item.get("source") or "inline")
                content = str(item.get("content") or "")
            else:
                source = str(item)
                content = self._read_document(workspace, source)
            chunks.extend(self._split_markdown(source, content))
        inline = input_data.get("content")
        if inline:
            chunks.extend(self._split_markdown("inline", str(inline)))
        return chunks

    def _read_document(self, workspace: Path, source: str) -> str:
        path = (workspace / source).resolve()
        try:
            path.relative_to(workspace.resolve())
        except ValueError:
            return ""
        if not path.exists() or not path.is_file():
            return ""
        return path.read_text(encoding="utf-8", errors="ignore")

    def _split_markdown(self, source: str, content: str) -> list[DocumentChunk]:
        if not content.strip():
            return []
        chunks: list[DocumentChunk] = []
        heading = "Document"
        buffer: list[str] = []
        for line in content.splitlines():
            if line.startswith("#"):
                if buffer:
                    chunks.append(DocumentChunk(source, heading, "\n".join(buffer).strip()))
                    buffer = []
                heading = line.lstrip("#").strip() or "Document"
            else:
                buffer.append(line)
        if buffer:
            chunks.append(DocumentChunk(source, heading, "\n".join(buffer).strip()))
        return [chunk for chunk in chunks if chunk.text]

    def _functional_requirements(self, chunks: list[DocumentChunk]) -> list[RequirementItem]:
        found: dict[str, RequirementItem] = {}
        for chunk in chunks:
            lowered = chunk.text.lower()
            for keyword, title in FUNCTIONAL_KEYWORDS.items():
                if keyword in lowered and keyword not in found:
                    req_id = f"REQ-{len(found) + 1:03d}"
                    found[keyword] = RequirementItem(
                        id=req_id,
                        title=title,
                        description=self._sentence_for_keyword(chunk, keyword),
                        priority=self._priority(lowered),
                        acceptance_criteria=[
                            f"{title} 可通过受支持的接口/入口正常使用。",
                            f"{title} 对成功与失败路径均产出可审计、可追踪的证据。",
                        ],
                        source_ref=f"{chunk.source}#{chunk.heading}",
                    )
        return list(found.values())

    def _non_functional_requirements(
        self,
        chunks: list[DocumentChunk],
    ) -> list[NonFunctionalRequirement]:
        found: dict[str, NonFunctionalRequirement] = {}
        for chunk in chunks:
            lowered = chunk.text.lower()
            for keyword, (category, _label) in NFR_KEYWORDS.items():
                if keyword in lowered and category not in found:
                    nfr_id = f"NFR-{len(found) + 1:03d}"
                    found[category] = NonFunctionalRequirement(
                        id=nfr_id,
                        category=category,
                        description=self._nfr_description(category),
                        priority=(
                            "high"
                            if category in {"security", "isolation", "disaster_recovery"}
                            else "medium"
                        ),
                        acceptance_criteria=self._nfr_acceptance(category),
                        source_ref=f"{chunk.source}#{chunk.heading}",
                    )
        return list(found.values())

    def _risks(
        self,
        chunks: list[DocumentChunk],
        nfrs: list[NonFunctionalRequirement],
    ) -> list[str]:
        risks = []
        text = "\n".join(chunk.text.lower() for chunk in chunks)
        if "docker" in text or "runner" in text:
            risks.append("RISK-001: Docker 执行边界必须防止宿主机逃逸与非受控的出网访问。")
        if "temporal" in text:
            risks.append("RISK-002: 工作流重试与信号必须跨崩溃保持幂等。")
        if "redis" in text or "dlq" in text:
            risks.append("RISK-003: 实时投影可能滞后，必须可从权威状态重放。")
        if "minio" in text or "artifact" in text:
            risks.append("RISK-004: 产物迁移必须先校验摘要再切换存储键。")
        if "gateway" in text or "oidc" in text:
            risks.append("RISK-005: 网关身份头必须防止内部调用方伪造。")
        for nfr in nfrs:
            if nfr.category == "disaster_recovery":
                risks.append("RISK-006: 备份恢复演练必须实际证明 RPO/RTO，而非仅在文档中声明。")
                break
        return risks

    def _traceability(
        self,
        requirements: list[RequirementItem],
        risks: list[str],
    ) -> list[RequirementTrace]:
        risk_ids = [risk.split(":", 1)[0] for risk in risks]
        traces = []
        for req in requirements:
            levels = ["unit", "contract"]
            if any(token in req.title.lower() for token in ["workflow", "runner", "网关"]):
                levels.append("integration")
            if any(token in req.title.lower() for token in ["agent", "a2a", "workflow"]):
                levels.append("e2e")
            traces.append(
                RequirementTrace(
                    requirement_id=req.id,
                    risk_ids=risk_ids[:3],
                    test_focus=req.acceptance_criteria,
                    recommended_test_levels=levels,
                )
            )
        return traces

    def _test_strategy(
        self,
        requirements: list[RequirementItem],
        nfrs: list[NonFunctionalRequirement],
        risks: list[str],
    ) -> TestStrategy:
        return TestStrategy(
            objective="验证企业级 Agent 工作流能力，覆盖从需求到执行诊断的全链路。",
            levels=["unit", "contract", "integration", "e2e", "regression"],
            priority_model="risk_based",
            entry_criteria=[
                "Agent 契约与 A2A Schema 已版本化。",
                "Temporal、PostgreSQL、Redis、MinIO 与 Runner Manager 配置可供集成测试使用。",
                "网关身份与审计传播预期已明确。",
            ],
            exit_criteria=[
                "所有高优先级需求均具备契约与集成测试覆盖。",
                "A2A 远程 Agent 调用的 discover/invoke/status 契约测试通过。",
                "Runner 隔离、Redis DLQ、产物迁移与备份演练路径通过回归门禁。",
            ],
            coverage_targets=[
                f"{len(requirements)} 条功能需求已映射到测试关注点。",
                f"{len(nfrs)} 条非功能需求已映射到验收标准。",
                f"{len(risks)} 项识别风险已由回归或集成测试覆盖。",
            ],
            regression_scope=[
                "PostgreSQL 原生仓储行为回归",
                "Runner Manager 隔离与队列持久化回归",
                "Redis Streams 重试/DLQ/重放回归",
                "MinIO 产物迁移摘要校验回归",
                "网关、可观测性、灾备演练与运维摘要回归",
                "A2A Agent Card 与 JSON-RPC 兼容性回归",
            ],
            automation_approach=[
                "基于 Agent Card 输入/输出 Schema 生成契约测试。",
                "结合本地 PostgreSQL 运行 Temporal 工作流集成测试。",
                "通过 ASGI 传输与 Docker Compose 冒烟测试运行远程 A2A 服务测试。",
            ],
        )

    def _sentence_for_keyword(self, chunk: DocumentChunk, keyword: str) -> str:
        pattern = re.compile(
            r"([^。\n.!?]*" + re.escape(keyword) + r"[^。\n.!?]*[。\n.!?]?)", re.IGNORECASE
        )
        match = pattern.search(chunk.text)
        if match:
            return match.group(1).strip(" -\t\n")
        return f"{chunk.heading}: {chunk.text[:240].strip()}"

    def _priority(self, text: str) -> str:
        if any(token in text for token in ["must", "required", "必须", "生产", "security", "安全"]):
            return "high"
        return "medium"

    def _nfr_description(self, category: str) -> str:
        return {
            "security": "企业安全控制必须保护身份、授权与高风险操作。",
            "isolation": "执行隔离必须防止不可信负载触达宿主机或未授权网络。",
            "observability": "链路追踪、指标、审计与运维摘要必须覆盖关键请求与工作流路径。",
            "disaster_recovery": "备份与恢复能力必须满足声明的 RPO/RTO 目标。",
            "reliability": "实时投递、工作流重试与后台处理必须容忍崩溃与积压。",
            "performance": "容量上限与延迟 SLO 必须明确且可测试。",
        }.get(category, f"{category} 需求必须可度量、可测试。")

    def _nfr_acceptance(self, category: str) -> list[str]:
        return {
            "security": [
                "OIDC/mTLS 身份从网关传播到 API。",
                "A2A 与工具调用受 RBAC 治理并纳入审计。",
            ],
            "isolation": [
                "仅 Runner Manager 可访问 Docker Socket。",
                "Runner 镜像要求摘要白名单并可选签名校验。",
            ],
            "observability": [
                "Trace ID 跨 API、Temporal、Redis、Runner 与 A2A 调用传播。",
                "运维摘要暴露队列、DLQ、备份与 OTel 状态。",
            ],
            "disaster_recovery": [
                "备份恢复演练产出通过/失败证据。",
                "RPO/RTO 阈值可配置并被强制。",
            ],
            "reliability": [
                "Redis 事件支持重试、待认领回收、DLQ 与重放。",
                "权威状态可重建实时投影。",
            ],
            "performance": [
                "任务队列容量与并发限制已文档化。",
                "SLO 告警覆盖积压、重试、DLQ 与延迟。",
            ],
        }.get(category, ["验收标准可度量。"])


# ─── JSON extraction helpers ──────────────────────────────


def _extract_json_object(text: str) -> dict[str, Any]:
    """Extract the first JSON object from a possibly noisy LLM response."""
    text = text.strip()
    fence = re.search(r"```(?:json)?\s*(.*?)```", text, re.DOTALL)
    if fence:
        text = fence.group(1).strip()
    start = text.find("{")
    if start < 0:
        raise ValueError("No JSON object found in LLM response")
    depth = 0
    in_string = False
    escape = False
    for idx in range(start, len(text)):
        char = text[idx]
        if escape:
            escape = False
            continue
        if char == "\\" and in_string:
            escape = True
            continue
        if char == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return json.loads(text[start : idx + 1])
    raise ValueError("Unbalanced JSON object in LLM response")


def _slug(value: str) -> str:
    slug = re.sub(r"[^0-9a-zA-Z\u4e00-\u9fff]+", "-", value).strip("-")
    return slug or "node"


def _parse_requirements(payload: dict[str, Any]) -> list[RequirementItem]:
    try:
        spec = payload.get("requirement_spec") or {}
        raw = spec.get("requirements") or []
        return [RequirementItem.model_validate(item) for item in raw if isinstance(item, dict)]
    except Exception:
        return []


def _parse_nfrs(payload: dict[str, Any]) -> list[NonFunctionalRequirement]:
    try:
        raw = payload.get("non_functional_requirements") or []
        return [
            NonFunctionalRequirement.model_validate(item)
            for item in raw
            if isinstance(item, dict)
        ]
    except Exception:
        return []


def _parse_risks(payload: dict[str, Any]) -> list[str]:
    try:
        spec = payload.get("requirement_spec") or {}
        return [str(item) for item in (spec.get("risks") or [])]
    except Exception:
        return []


def _parse_strategy(payload: dict[str, Any]) -> TestStrategy:
    try:
        return TestStrategy.model_validate(payload.get("test_strategy") or {})
    except Exception:
        return TestStrategy(objective="根据需求生成测试策略。")


def _parse_traces(payload: dict[str, Any]) -> list[RequirementTrace]:
    try:
        raw = payload.get("traceability") or []
        return [RequirementTrace.model_validate(item) for item in raw if isinstance(item, dict)]
    except Exception:
        return []
