"""Built-in RBAC permissions and roles."""

PERMISSIONS: dict[str, str] = {
    "session:create": "Create conversation sessions",
    "session:read": "Read sessions and conversation history",
    "session:message": "Send messages to agents",
    "agent:read": "Read agent configuration and status",
    "agent:invoke": "Invoke agents",
    "agent:manage": "Add/remove remote A2A services and manage agent registry",
    "a2a:invoke": "Invoke agents through A2A JSON-RPC",
    "execution:read": "Read execution status and diagnosis",
    "execution:invoke": "Start test and agent executions",
    "knowledge:read": "Search knowledge bases",
    "knowledge:write": "Ingest and manage knowledge sources",
    "test_case:read": "Read test cases",
    "test_case:write": "Create and update test cases",
    "skill:read": "Read installed skill definitions",
    "config:read": "Read system configuration",
    "config:write": "Modify system configuration",
    "mcp:manage": "Manage MCP servers and bindings",
    "tool:invoke": "Invoke local or remote tools",
    "audit:read": "Read and verify audit records",
    "trace:read": "Read full-chain execution traces",
    "identity:manage": "Manage actors and credentials",
    "artifact:read": "Read immutable artifacts and versions",
    "artifact:write": "Create artifacts, versions, and lineage links",
    "artifact:archive": "Archive logical artifacts",
    "policy:read": "Read risk policies and decisions",
    "policy:manage": "Create and update risk policies",
    "workflow:read": "Read durable workflow state",
    "workflow:cancel": "Cancel durable workflows",
    "workflow:resume": "Request workflow resumption",
    "human_task:read": "Read human approval tasks",
    "human_task:claim": "Claim and release human tasks",
    "human_task:approve": "Approve or reject human tasks",
    "human_task:manage": "Manage all human tasks",
    "evaluation:read": "Read evaluation suites and runs",
    "evaluation:write": "Create suites and submit evaluation results",
    "ops:read": "Read production operations and SLO summaries",
}

ROLE_PERMISSIONS: dict[str, set[str]] = {
    "viewer": {"session:read", "agent:read", "config:read", "artifact:read"},
    "operator": {
        "session:create",
        "session:read",
        "session:message",
        "agent:read",
        "agent:invoke",
        "agent:manage",
        "a2a:invoke",
        "execution:read",
        "execution:invoke",
        "knowledge:read",
        "knowledge:write",
        "test_case:read",
        "test_case:write",
        "skill:read",
        "config:read",
        "tool:invoke",
        "artifact:read",
        "artifact:write",
        "policy:read",
        "workflow:read",
        "workflow:resume",
        "human_task:read",
        "evaluation:read",
        "evaluation:write",
    },
    "reviewer": {
        "session:read",
        "agent:read",
        "config:read",
        "audit:read",
        "trace:read",
        "artifact:read",
        "policy:read",
        "workflow:read",
        "workflow:resume",
        "human_task:read",
        "human_task:claim",
        "human_task:approve",
        "evaluation:read",
    },
    "admin": set(PERMISSIONS),
    "agent": {
        "agent:invoke",
        "a2a:invoke",
        "tool:invoke",
        "session:read",
        "artifact:read",
        "artifact:write",
        "workflow:read",
        "workflow:resume",
    },
}
